<?php
//DB Connection Code
$con=mysqli_connect('localhost','pi_username','pi_pwd');
$db=mysqli_select_db($con,'db_name');



//Importing PHP Mailer 
require '/usr/share/php/libphp-phpmailer/class.phpmailer.php';
require '/usr/share/php/libphp-phpmailer/class.smtp.php';
$mail = new PHPMailer;





  



  
  $resultset = [];
      date_default_timezone_set('Asia/Kolkata');
   $yesterday = date('Y-m-d',strtotime("-1 days"));
     $start =  $yesterday;
        $fin = date("Y-m-d");
    
  
  $result=mysqli_query($con,"select user_name as 'Name Of Employee', MIN(rfid_presented_datetime) as 'CheckIn Time',MAX(rfid_presented_datetime) as 'CheckOut Time', TIMEDIFF(MAX(rfid_presented_datetime),MIN(rfid_presented_datetime)) as 'Total Hours' from access_log where rfid_presented_datetime like '$start%' group by user_name");
    while($row=mysqli_fetch_assoc($result)) {
      array_push($resultset,$row);
    } 
    
    
    $fp = fopen('file.csv', 'w');
$placed_header = false;
 foreach ($resultset  as $row) {
    // add header to table Code for CSV
    if(!$placed_header) {
        fputcsv($fp, array_keys($row));
        $placed_header = true;
    }
    // place row of data 
    fputcsv($fp, array_values($row));
}

fclose($fp);
    
    
//PHPMailer Object Code For Mail
$mail->setFrom('username@website.com');
$mail->addAddress('xyz@xyz.com');
$mail->Subject = 'Attendance report for:'.$start;
$mail->Body = '<h2>Hello! \nHeres todays attendance report!</h2><p style="color:Blue;">
PFA</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'smtp.website.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'username@website.com';
$mail->Password = 'pwd';
$mail->addAttachment('file.csv'); 
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  header("location:index.php");
}
    
  

?>
